# schema for indieweb_micropub.settings
indieweb_micropub.settings:
  type: config_object
  label: 'Indieweb micropub'
  mapping:
    micropub_enable:
      type: boolean
      label: 'Enable micropub endpoint'
    micropub_expose_link_tag:
      type: boolean
      label: 'Expose micropub link tag'
    micropub_enable_update:
      type: boolean
      label: 'Enable post updates'
    micropub_enable_delete:
      type: boolean
      label: 'Enable post deletes'
    micropub_enable_source:
      type: boolean
      label: 'Enable post queries'
    micropub_enable_geo:
      type: boolean
      label: 'Enable geo query'
    micropub_enable_category:
      type: boolean
      label: 'Enable category request'
    micropub_category_vocabulary:
      type: string
      label: 'The vocabulary to get the terms for'
    micropub_media_enable:
      type: boolean
      label: 'Enable micropub media endpoint'
    micropub_log_payload:
      type: boolean
      label: 'Whether to log the payload'
    note_create_node:
      type: boolean
      label: 'Enable note support'
    note_status:
      type: integer
      label: 'Whether the note is published or not'
    note_node_type:
      type: string
      label: 'The node type for the note'
    note_content_field:
      type: string
      label: 'The node content field for the note'
    note_upload_field:
      type: string
      label: 'The node upload field for the note'
    note_tags_field:
      type: string
      label: 'The node tags field for the note'
    note_geo_field:
      type: string
      label: 'The node geo field for the note'
    note_uid:
      type: integer
      label: 'The user id of the note'
    article_create_node:
      type: boolean
      label: 'Enable article'
    article_status:
      type: integer
      label: 'Whether the article is published or not'
    article_node_type:
      type: string
      label: 'The node type for the article'
    article_content_field:
      type: string
      label: 'The node content field for the article'
    article_upload_field:
      type: string
      label: 'The node upload field for the article'
    article_tags_field:
      type: string
      label: 'The node tags field for the article'
    article_geo_field:
      type: string
      label: 'The node geo field for the article'
    article_uid:
      type: integer
      label: 'The user id of the article'
    like_create_node:
      type: boolean
      label: 'Enable like'
    like_status:
      type: integer
      label: 'Whether the like is published or not'
    like_node_type:
      type: string
      label: 'The node type for the like'
    like_content_field:
      type: string
      label: 'The node content field for the like'
    like_link_field:
      type: string
      label: 'The node link field for the like'
    like_auto_send_webmention:
      type: boolean
      label: 'Whether to automatically send a webmention to the url found in the link field'
    like_tags_field:
      type: string
      label: 'The node tags field for the like'
    like_upload_field:
      type: string
      label: 'The node upload field for the like'
    like_uid:
      type: integer
      label: 'The user id of the like'
    reply_create_node:
      type: boolean
      label: 'Enable reply'
    reply_status:
      type: integer
      label: 'Whether the reply is published or not'
    reply_node_type:
      type: string
      label: 'The node type for the reply'
    reply_content_field:
      type: string
      label: 'The node content field for the reply'
    reply_link_field:
      type: string
      label: 'The node link field for the reply'
    reply_auto_send_webmention:
      type: boolean
      label: 'Whether to automatically send a webmention to the url found in the link field'
    reply_tags_field:
      type: string
      label: 'The node tags field for the reply'
    reply_upload_field:
      type: string
      label: 'The node upload field for the reply'
    reply_create_comment:
      type: boolean
      label: 'Create comments if target is webmention url.'
    reply_uid:
      type: integer
      label: 'The user id of the reply'
    repost_create_node:
      type: boolean
      label: 'Enable repost'
    repost_status:
      type: integer
      label: 'Whether the repost is published or not'
    repost_node_type:
      type: string
      label: 'The node type for the repost'
    repost_content_field:
      type: string
      label: 'The node content field for the repost'
    repost_link_field:
      type: string
      label: 'The node link field for the repost'
    repost_auto_send_webmention:
      type: boolean
      label: 'Whether to automatically send a webmention to the url found in the link field'
    repost_tags_field:
      type: string
      label: 'The node tags field for the repost'
    repost_upload_field:
      type: string
      label: 'The node upload field for the repost'
    repost_uid:
      type: integer
      label: 'The user id of the repost'
    bookmark_create_node:
      type: boolean
      label: 'Enable bookmark'
    bookmark_status:
      type: integer
      label: 'Whether the bookmark is published or not'
    bookmark_node_type:
      type: string
      label: 'The node type for the bookmark'
    bookmark_content_field:
      type: string
      label: 'The node content field for the bookmark'
    bookmark_link_field:
      type: string
      label: 'The node link field for the repost'
    bookmark_auto_send_webmention:
      type: boolean
      label: 'Whether to automatically send a webmention to the url found in the link field'
    bookmark_tags_field:
      type: string
      label: 'The node tags field for the bookmark'
    bookmark_upload_field:
      type: string
      label: 'The node upload field for the bookmark'
    bookmark_uid:
      type: integer
      label: 'The user id of the bookmark'
    event_create_node:
      type: boolean
      label: 'Enable event'
    event_status:
      type: integer
      label: 'Whether the event is published or not'
    event_node_type:
      type: string
      label: 'The node type for the event'
    event_content_field:
      type: string
      label: 'The node content field for the event'
    event_date_field:
      type: string
      label: 'The node link field for the event'
    event_tags_field:
      type: string
      label: 'The node tags field for the event'
    event_geo_field:
      type: string
      label: 'The node geo field for the event'
    event_link_field:
      type: string
      label: 'The node link field for the event'
    event_upload_field:
      type: string
      label: 'The node upload field for the event'
    event_uid:
      type: integer
      label: 'The user id of the event'
    rsvp_create_node:
      type: boolean
      label: 'Enable RSVP'
    rsvp_status:
      type: integer
      label: 'Whether the RSVP is published or not'
    rsvp_node_type:
      type: string
      label: 'The node type for the RSVP'
    rsvp_content_field:
      type: string
      label: 'The node content field for the RSVP'
    rsvp_link_field:
      type: string
      label: 'The node link field for the RSVP'
    rsvp_auto_send_webmention:
      type: boolean
      label: 'Whether to automatically send a webmention to the url found in the link field'
    rsvp_rsvp_field:
      type: string
      label: 'The node RSVP field for the RSVP'
    rsvp_tags_field:
      type: string
      label: 'The node tags field for the rsvp'
    rsvp_upload_field:
      type: string
      label: 'The node upload field for the rsvp'
    rsvp_uid:
      type: integer
      label: 'The user id of the RSVP'
    issue_create_node:
      type: boolean
      label: 'Enable issue'
    issue_status:
      type: integer
      label: 'Whether the issue is published or not'
    issue_node_type:
      type: string
      label: 'The node type for the issue'
    issue_content_field:
      type: string
      label: 'The node content field for the issue'
    issue_link_field:
      type: string
      label: 'The node link field for the issue'
    issue_auto_send_webmention:
      type: boolean
      label: 'Whether to automatically send a webmention to the url found in the link field'
    issue_upload_field:
      type: string
      label: 'The node upload field for the issue'
    issue_tags_field:
      type: string
      label: 'The node tags field for the issue'
    issue_uid:
      type: integer
      label: 'The user id of the issue'
    checkin_create_node:
      type: boolean
      label: 'Enable checkin'
    checkin_status:
      type: integer
      label: 'Whether the checkin is published or not'
    checkin_node_type:
      type: string
      label: 'The node type for the checkin'
    checkin_content_field:
      type: string
      label: 'The node content field for the checkin'
    checkin_tags_field:
      type: string
      label: 'The node tags field for the checkin'
    checkin_geo_field:
      type: string
      label: 'The node geo field for the checkin'
    checkin_link_field:
      type: string
      label: 'The node link field for the checkin'
    checkin_upload_field:
      type: string
      label: 'The node upload field for the checkin'
    checkin_uid:
      type: integer
      label: 'The user id of the checkin'
    geocache_create_node:
      type: boolean
      label: 'Enable geocache'
    geocache_status:
      type: integer
      label: 'Whether the geocache is published or not'
    geocache_node_type:
      type: string
      label: 'The node type for the geocache'
    geocache_content_field:
      type: string
      label: 'The node content field for the geocache'
    geocache_tags_field:
      type: string
      label: 'The node tags field for the geocache'
    geocache_geo_field:
      type: string
      label: 'The node geo field for the geocache'
    geocache_link_field:
      type: string
      label: 'The node link field for the geocache'
    geocache_upload_field:
      type: string
      label: 'The node upload field for the geocache'
    geocache_uid:
      type: integer
      label: 'The user id of the geocache'
    geocache_geocache_field:
      type: string
      label: 'The node geocache field for the log type'