# schema for indieweb_websub.settings
indieweb_websub.settings:
  type: config_object
  label: 'Indieweb WebSub'
  mapping:
    hub_endpoint:
      type: string
      label: 'WebSub Hub endpoint'
    expose_link_tag:
      type: boolean
      label: 'Expose WebSub link tag'
    log_payload:
      type: boolean
      label: 'Log the payloads'
    node_element:
      type: string
      label: 'Add WebSub element to node edit forms'
    send_pub_handler:
      type: string
      label: 'How to handle the webmention send queue'
    resubscribe_handler:
      type: string
      label: 'How to resubscribe to WebSub subscriptions'
    pages:
      type: string
      label: 'On which pages to expose the hub links'
    micropub_publish_to_hub:
      type: boolean
      label: 'Send publication to hub when posting via micropub'
    microsub_api_subscribe:
      type: boolean
      label: 'Subscribe to WebSub if a feed is created via the Microsub API'
